"""add region to vehicles

Revision ID: a99cd3c3f2d6
Revises: 285193c59037
Create Date: 2026-07-12 12:35:21.608623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a99cd3c3f2d6'
down_revision: Union[str, Sequence[str], None] = '285193c59037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('region', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_vehicles_region'), 'vehicles', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_region'), table_name='vehicles')
    op.drop_column('vehicles', 'region')
    # ### end Alembic commands ###
